# Keys for LocalizationManger to use in source code: MIT License
# @author Vladimir Petrenko
tool
class_name LocalizationKeys

const BOY = "BOY"
const GIRL = "GIRL"
const JOHN = "JOHN"
const QUEST_HEADER = "QUEST_HEADER"
const QUEST_DESCRIPTION = "QUEST_DESCRIPTION"
const QUEST_START_01 = "QUEST_START_01"
const QUEST_START_02 = "QUEST_START_02"
const QUEST_START_03 = "QUEST_START_03"
const QUEST_START_04 = "QUEST_START_04"
const QUEST_START_05 = "QUEST_START_05"
const QUEST_STARTET = "QUEST_STARTET"
const QUEST_START_NAME = "QUEST_START_NAME"
const QUEST_START_DESCRIPTION = "QUEST_START_DESCRIPTION"
const QUEST_SPEACK_JOHN_01 = "QUEST_SPEACK_JOHN_01"
const QUEST_SPEACK_JOHN_02 = "QUEST_SPEACK_JOHN_02"
const QUEST_DELIVERY = "QUEST_DELIVERY"
const QUEST_STARTED_TEXT = "QUEST_STARTED_TEXT"
const QUEST_ENDED_TEXT = "QUEST_ENDED_TEXT"
const ITEM_HEALTH = "ITEM_HEALTH"
const ITEM_HEALTH_BIG = "ITEM_HEALTH_BIG"

const KEYS = [
 "BOY",
 "GIRL",
 "JOHN",
 "QUEST_HEADER",
 "QUEST_DESCRIPTION",
 "QUEST_START_01",
 "QUEST_START_02",
 "QUEST_START_03",
 "QUEST_START_04",
 "QUEST_START_05",
 "QUEST_STARTET",
 "QUEST_START_NAME",
 "QUEST_START_DESCRIPTION",
 "QUEST_SPEACK_JOHN_01",
 "QUEST_SPEACK_JOHN_02",
 "QUEST_DELIVERY",
 "QUEST_STARTED_TEXT",
 "QUEST_ENDED_TEXT",
 "ITEM_HEALTH",
 "ITEM_HEALTH_BIG"
]